name: minikube-e2e-docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Needed for running workflows locally via `act` as it is not
      # present in the `catthehacker/ubuntu:act-latest` image.
      - uses: azure/setup-kubectl@v4
        with:
          version: "v1.34.3"

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Setup Minikube
        uses: medyagh/setup-minikube@v0.0.21
        with:
          minikube-version: "1.37.0"
          kubernetes-version: "1.34.3"
          container-runtime: docker
          wait: all
          start-args: "--force=true --delete-on-failure --profile=e2e-docker"
          # github token: ${{ secrets.GITHUB_TOKEN }} Uncomment if we have API limit issues

      - name: Deploy test pod
        run: |
          kubectl create -f assets/busybox-pod.yaml
          kubectl wait --for=condition=Ready pod/busybox-sleep

      - name: Build
        run: |
          make

      - name: Run ksniff with ephemeral container
        run: |
          sleep 60 && pkill kubectl-sniff & 
          set +e
          ./kubectl-sniff busybox-sleep --namespace default --output-file /tmp/output.pcap
          set -e
          if [ ! -f /tmp/output.pcap ]; then
            echo "PCAP not created"
            exit 1
          fi

      - if: failure()
        name: Check pod and events
        run: |
          kubectl get pods 
          kubectl get events
          kubectl describe pod/busybox-sleep

      - if: always()
        name: Delete cluster
        run: |
          minikube delete --profile=e2e-docker
