name: Release

on:
  release:
    types: [published]

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24.11

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpcap-dev gcc

      - name: Build
        run: make all

      - name: Package
        run: make package

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ksniff.zip
          asset_name: ksniff.zip
          asset_content_type: application/zip

      # - name: Update Krew index
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: bash scripts/update-krew-index.sh
